{"name": "Переход в ленту заказов со страницы логина", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: Список заказов не отобразился\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16", "trace": "self = <tests.test_constructor.TestConstructorFromLogin object at 0x000001DE7E160FC0>\ndriver = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"b8559b00-2866-463e-af81-57b0ae215004\")>\n\n    @allure.title(\"Переход в ленту заказов со страницы логина\")\n    def test_go_to_order_feed_from_login(self, driver):\n        with allure.step(\"Открываем страницу логина\"):\n            self.driver.get(f\"{BASE_URL}/login\")\n            WebDriverWait(self.driver, 10).until(\n                EC.visibility_of_element_located(LoginPageLocators.LOGIN_BUTTON)\n            )\n        with allure.step(\"Кликаем кнопку 'Лента заказов'\"):\n            self.main_page.go_to_order_feed()\n        with allure.step(\"Проверяем загрузку ленты заказов\"):\n            assert self.main_page.wait_for_url_contains(\"/feed\"), \"Не открылась лента заказов\"\n            WebDriverWait(self.driver, 10).until(\n                EC.visibility_of_element_located(OrderFeedLocators.ORDER_FEED_SECTION),\n                \"Заголовок ленты заказов не отобразился\"\n            )\n>           WebDriverWait(self.driver, 10).until(\n                EC.visibility_of_element_located(OrderFeedLocators.ORDER_LIST),\n                \"Список заказов не отобразился\"\n            )\n\ntests\\test_constructor.py:50: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"b8559b00-2866-463e-af81-57b0ae215004\")>\nmethod = <function visibility_of_element_located.<locals>._predicate at 0x000001DE7E2A16C0>, message = 'Список заказов не отобразился'\n\n    def until(self, method: Callable[[WebDriver], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: Список заказов не отобразился\nE       Stacktrace:\nE       RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nE       WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5\nE       NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5\nE       dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\nvenv\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py:101: TimeoutException"}, "steps": [{"name": "Открываем страницу логина", "status": "passed", "start": 1748199252666, "stop": 1748199254588}, {"name": "Кликаем кнопку 'Лента заказов'", "status": "passed", "start": 1748199254588, "stop": 1748199275931}, {"name": "Проверяем загрузку ленты заказов", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: Список заказов не отобразился\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n", "trace": "  File \"C:\\Users\\windw\\PycharmProjects\\Diplom\\Diplom_3\\tests\\test_constructor.py\", line 50, in test_go_to_order_feed_from_login\n    WebDriverWait(self.driver, 10).until(\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n        EC.visibility_of_element_located(OrderFeedLocators.ORDER_LIST),\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        \"Список заказов не отобразился\"\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"C:\\Users\\windw\\PycharmProjects\\Diplom\\Diplom_3\\venv\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 101, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1748199275931, "stop": 1748199287094}], "parameters": [{"name": "driver", "value": "'firefox'"}], "start": 1748199252666, "stop": 1748199287096, "uuid": "a319a95f-5564-4f97-be39-d35c4720548e", "historyId": "25983787fb7ec0d558a6b2bf6b3fb078", "testCaseId": "e586d6ea6551d59a7239cf3b5da65576", "fullName": "tests.test_constructor.TestConstructorFromLogin#test_go_to_order_feed_from_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_constructor"}, {"name": "subSuite", "value": "TestConstructorFromLogin"}, {"name": "host", "value": "Gemini_78"}, {"name": "thread", "value": "19464-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_constructor"}]}